[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "multipred"
description = "Code to replicate fmri multipred study"
requires-python = ">=3.8"
license = {text = "MIT"}
dynamic = ["version", "readme"]
dependencies = [
    "numpy==2.2.3",
    "pandas==2.2.3",
    "matplotlib==3.10.1",
    "seaborn==0.13.2",
    "pingouin==0.5.5",
    "scipy==1.15.2",
    "statsmodels==0.14.4",
    "nilearn==0.11.1",
    "nibabel==5.3.2",
]
authors = [
    {name="Marc Sabio-Albert", email="marcsabioalbert@gmail.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
repository = "https://github.com/memory-formation/multipred-fmri"

[tool.setuptools.packages.find]
include = ["multipred*"]

[tool.setuptools.dynamic]
version = {attr = "multipred.__version__"}
readme = {file = ["README.md"], content-type = "text/markdown"}
